theme:
  name: material
  palette:
    primary: teal
  logo: img/favicon_io/favicon.ico
  favicon: img/favicon_io/favicon.ico
site_name: Netts
repo_name: alan-turing-institute/netts
repo_url: https://github.com/alan-turing-institute/netts
icon:
  repo: fontawesome/brands/github-alt

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
      base_path: "examples/"
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - mkdocs-click
  - attr_list
  - md_in_html
  - admonition

nav:
  - Overview: index.md
  - Getting Started: install.md
  - Usage:
      - Command Line:
          - Basic: cli_basics.md
          - Options: cli.md
          - Advanced: configuration.md
      - Python: python_basics.md
      - Analysing networks: post-processing.md
  - Pipeline: pipeline.md
